bookchange/bookchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(("catalog.urls", 'catalog'), namespace='catalog')),
                  path('', include(("messenger.urls", 'messenger'), namespace='messenger')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookchange/catalog/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('reg/', views.RegistrationView.as_view(), name='reg'),

    path('', login_required(views.MainListView.as_view()), name='main'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('book/create/', login_required(views.BookCreateView.as_view()), name='addBook'),
    path('book/<int:pk>', login_required(views.book), name='book'),
    path('book/<int:pk>/update', login_required(views.BookUpdateView.as_view()), name='updateBook'),
    path('book/<int:pk>/delete', login_required(views.BookDeleteView.as_view()), name='deleteBook'),

    path('author/create/', login_required(views.AuthorCreateView.as_view()), name='addAuthor'),
    path('author/<int:pk>/update', login_required(views.AuthorUpdateView.as_view()), name='updateAuthor'),
    path('author/<int:pk>/delete', login_required(views.AuthorDeleteView.as_view()), name='deleteAuthor'),

    path('profile/create/', login_required(views.ProfileCreateView.as_view()), name='addProfile'),
    path('profile/<int:pk>', login_required(views.profile), name='profile'),
    path('profile/<int:pk>/update', login_required(views.ProfileUpdateView.as_view()), name='updateProfile'),

    path('review/create/<int:pk>', login_required(views.ReviewCreateView.as_view()), name='addReview'),
    path('review/<int:pk>/update', login_required(views.ReviewUpdateView.as_view()), name='updateReview'),
    path('review/<int:pk>/delete', login_required(views.ReviewDeleteView.as_view()), name='deleteReview'),

]

bookchange/messenger/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('dialogs/', login_required(views.DialogsView.as_view()), name='dialogs'),
    path('dialogs/create/<int:user_id>/<int:book_id>',
         login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    path('dialogs/<int:chat_id>', login_required(views.MessagesView.as_view()), name='dialog'),
]

bookchange/catalog/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User


class Genre(models.Model):
    genreName = models.CharField(max_length=30)

    def __str__(self):
        return self.genreName

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ['genreName']


class Author(models.Model):
    first_name = models.CharField(max_length=100,verbose_name='Имя автора')
    last_name = models.CharField(max_length=100,verbose_name='Фамилия автора')

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['last_name']


class Book(models.Model):
    title = models.CharField('Название книги', max_length=100)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, verbose_name='Автор книги')
    summary = models.TextField('Краткое описание', max_length=1000, default=' ', blank=True)
    genre = models.ManyToManyField(Genre, blank=True, verbose_name='Жанры книги')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(default='img/books/default.webp', upload_to='img/books', blank=True,
                              verbose_name='Фотография книги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # noinspection PyUnresolvedReferences
        return reverse('book', kwargs={'pk': str(self.id)})

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ['title']


class Review(models.Model):
    critic = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    text = models.TextField('Рецензия', max_length=1000)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'
        ordering = ['book']


class BookOfMonth(models.Model):
    title = models.CharField('Название книги', max_length=50)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField('Краткое описание', max_length=1000,
                               default=' ')
    dayOfBook = models.DateField('Месяц книги')

    image = models.ImageField(upload_to='images/booksOfMonth')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Книга месяца'
        verbose_name_plural = 'Книги месяца'
        ordering = ['dayOfBook']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='img/profiles/default.jpg', upload_to='img/profiles', blank=True,
                              verbose_name='Ваш аватар')
    genre = models.ManyToManyField(Genre, blank=True, verbose_name='Любимые жанры',
                                   help_text="Удерживайте “Control“ (или “Command“ на Mac), чтобы выбрать несколько значений.")

    def get_absolute_url(self):
        # noinspection PyUnresolvedReferences
        return reverse('profile', kwargs={'pk': str(self.id)})


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        # noinspection PyUnresolvedReferences
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

bookchange/catalog/views.py
from django.contrib.auth.forms import UserCreationForm

from django.db.models.functions import datetime
from django.shortcuts import render
from django.views import View

from .models import *
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView


def get_preferred_sorted_books(user, books):
    not_sorted_tuples = tuple(((b.genre.all() & user.profile.genre.all()).count(), b) for b in books)
    sorted_tuple = sorted(not_sorted_tuples, key=lambda item: item[0], reverse=True)
    return [x[1] for x in sorted_tuple]


def get_book_of_month():
    today = datetime.datetime.now()
    return BookOfMonth.objects.get(dayOfBook__year=today.year, dayOfBook__month=today.month)


def profile(request, pk):
    user = User.objects.get(id=pk)
    books = Book.objects.filter(owner_id=pk)
    prof = Profile.objects.get(user_id=pk)
    return render(request, 'catalog/profile_of_user.html',
                  {'user': user,
                   'books': books,
                   'book_of_month': get_book_of_month(),
                   'profile': prof})


class MainListView(View):
    def get(self, request):
        books = Book.objects.exclude(owner_id=request.user.id)
        return render(request, 'catalog/main.html',
                      {'books': get_preferred_sorted_books(request.user, books),
                       'user.id': request.user.id,
                       'book_of_month': get_book_of_month()})


def book(request, pk):
    book = Book.objects.get(id=pk)
    return render(request, 'catalog/book.html', {'book': book,
                                                 'book_of_month': get_book_of_month()})


class RegistrationView(CreateView):
    form_class = UserCreationForm
    success_url = '/'
    template_name = "catalog/reg.html"


class BookCreateView(CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'genre', 'image']
    success_url = '/'

    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        return super().form_valid(form)


class BookUpdateView(UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'genre', 'image']
    success_url = '/'


class BookDeleteView(DeleteView):
    model = Book
    success_url = '/'


class AuthorCreateView(CreateView):
    model = Author
    fields = '__all__'
    success_url = '/book/create/'


class AuthorUpdateView(UpdateView):
    model = Author
    fields = '__all__'
    success_url = '/book/'


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = '/'


class ProfileCreateView(CreateView):
    model = Profile
    fields = ['image', 'genre']
    success_url = '/'


class ProfileUpdateView(UpdateView):
    model = Profile
    fields = ['image', 'genre']
    success_url = '/'


class ReviewCreateView(CreateView):
    model = Review
    fields = ['text']
    success_url = '/'

    def form_valid(self, form):
        form.instance.critic_id = self.request.user.id
        form.instance.book_id = self.kwargs['pk']
        return super().form_valid(form)


class ReviewUpdateView(UpdateView):
    model = Review
    fields = ['text']
    success_url = '/'


class ReviewDeleteView(DeleteView):
    model = Review
    success_url = '/'

bookchange/catalog/templates/catalog/addBook.html
{% extends 'catalog/index.html' %}
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <style type="text/css">
        .photo {
            display: flex;
        }
        p{
            margin-right: 4.25%;
        }
        .allText{
            margin: 15px;
        }
        h3{
            margin-bottom: 15px;
        }

    </style>
    {% block title %}
Добавить книгу
{% endblock %}
  </head>
  {% block content %}
  <body>
  <h3>Добавление книги</h3>
  <form>
    <div class="photo">
      <p>Выберите фото книги:  </p>
      <input type="file" name="photo" multiple accept="image/*,image/jpeg" />
    </div>
    <div class="row mb-3">
      <label for="inputName3" class="col-sm-2 col-form-label"
      >Название книги: </label
      >
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputName3" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputAutor3" class="col-sm-2 col-form-label"
      >ФИО автора: </label
      >
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputAutor3" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputAbout3" class="col-sm-2 col-form-label"
      >Коротко о книге: </label
      >
      <div class="col-sm-10">
        <textarea class="form-control" id="inputAbout3" cols="15" rows="10"></textarea>
      </div>
    </div>
    <div class="col-12 d-flex justify-content-center"><button type="submit" class="btn btn-primary ml-10">Сохранить</button></div>
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
{% endblock %}

bookchange/catalog/templates/catalog/book.html
{% extends 'catalog/index.html' %}
{% block title %}Книга: {{ book.title }}{% endblock %}
  {% block content %}
<div class="page_userProfile">
      <div class="card_userProfile">
        <img src="{{MEDIA_URL}}{{ book.image.url}}" />
      </div>
      <div class="blok2_userProfile">
        <div class="card2_userProfile">
          <div class="book_name_userProfile"><h2>{{ book.title }} {{ book.author }}</h2></div>
          <p class="title_userProfile">
            Жанры:{% for g in book.genre.all %} {{ g.genreName }}{% endfor %}
          </p>
          <p>
            {{book.summary}}
          </p>
          {% if request.user == book.owner %}
          <div class="knopki_userProfile">
            <form action="{% url 'catalog:updateBook' book.id %}"><button class="form_button">Изменить информацию о книге</button></form>
            <form action="{% url 'catalog:deleteBook' book.id %}"><button class="form_button">Удалить книгу</button></form>
          </div>
          {% else %}
          <div class="knopki_userProfile">
            <form action="{% url 'messenger:create_dialog' book.owner.id book.id %}"><button class="form_button">Написать владельцу книги</button></form>
            <form action="{% url 'catalog:profile' book.owner.id %}"><button class="form_button">Владелец книги</button></form>
          </div>
          {% endif %}
          <form action="{% url 'catalog:addReview' book.id %}"><button class="form_button">Написать рецензию об этой книге</button></form>
        </div>
        <h2>Отзывы</h2>
        {% if book.reviews.all %}
        {% for review in book.reviews.all %}
        <div class="space1">
        {% include 'catalog/review-item.html' with review=review %}
          </div>
        {% endfor %}
        {% else %}
        <p>Никто ещё не написал свою рецензию</p>
        {% endif %}
      </div>
    </div>
{% endblock %}

bookchange/catalog/templates/catalog/book_form.html
{% extends "catalog/index.html" %}
{% block title %} Форма книги {% endblock %}
{% block content %}
<div class="form_form">
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" class="form_button" value="Добавить книгу для обмена" />
</form>
Нет подходящего автора?  <a href="{% url 'catalog:addAuthor'%}" class="text-danger">Добавить автора</a>
      </div>
{% endblock %}

bookchange/catalog/templates/catalog/index.html
<!doctype html>
<html lang="ru">
  <head>
      <link rel="shortcut icon" href="/media/img/icon/icon.gif" type="image/gif">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <style type="text/css">
        .space{
            position: fixed; left: 19%;
            width: 1000px;
        }
        .space1{
        margin-left: auto;
        margin-right: auto;
        width: 80%;
      }
        .space2{
        margin-left: auto;
        margin-right: auto;
        width: 80%;
            font-weight: 700;
      }
        .container_message {
    border: 2px solid #dedede;
    background-color: #f1f1f1;
    border-radius: 5px;
    padding: 10px;
    margin: 10px 0;

    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 500px;
    margin: auto;
}
        .container_message::after {
    content: "";
    clear: both;
    display: table;
}

/* Style images */
.container_message img {
    float: left;
    max-width: 60px;
    width: 100%;
    margin-right: 20px;
    border-radius: 50%;
}
        .darker {
    border-color: #ccc;
    background-color: #ddd;
}
    .blok2{
        margin-right: 30px;
        margin-left: 20px;
      }
      .card2 {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: auto;
        text-align: center;
        padding: 10px;
        background: white;
        border-radius: 5px;
        margin-right: 30px;
        margin-left: 20px;
      }
      .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 500px;
        margin: auto;
        text-align: center;
        padding: 10px;
        background: white;
        border-radius: 5px;
        margin-left: 30px;
      }

      .footer{
    position: absolute;
    left: 0;
    bottom: 0;
    width: 100%;
    height: 80px;
    z-index: 2;
}

.title {
        color: grey;
        font-size: 18px;
      }
.container_trade {
        align-self: flex-start;
        border: 2px solid #dedede;
        background-color: #f1f1f1;
        border-radius: 5px;
        padding: 10px;
        margin: 5px 0;
      }

      /* Clear floats */
      .container_trade::after {
        content: "";
        clear: both;
        display: table;
      }

      /* Style images */
      .container_trade img {
        float: left;
        max-width: 100px;
        width: 100%;
        height: 100%;
        margin-right: 20px;
        border-radius: 10%;
      }

.container_book {
    border: 2px solid #dedede;
    background-color: #f1f1f1;
    border-radius: 10px;
    padding: 10px;
    margin: 5px 0;
}
.container_book img {
        float: left;
        max-width: 100px;
        width: 100%;
        height: 100%;
        margin-right: 20px;
        border-radius: 10%;
      }

/* Clear floats */
.container::after {
    content: "";
    clear: both;
    display: table;
}

/* Style images */
.container img {
    float: left;
    max-width: 100px;
    width: 100%;
    height: 100%;
    margin-right: 20px;
    border-radius: 10%;
}

.book_name {
    font-weight: bold;
    margin-top: 12px;
    color: black;
}

.book_author{
    padding-top: 0px;
    color: rgb(82, 81, 81);
    margin-top: 15px;
}

.book_genre{

    color: rgb(146, 150, 146);
    padding-left: 120px;
}


        h5 {
            text-align: center;
        }
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 500px;
            margin: auto;
            text-align: center;
            padding: 10px;
        }

        .title_card {
            color: grey;
            font-size: 18px;
        }

        button {
            border: none;
            outline: 0;
            display: inline-block;
            padding: 8px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
            border-radius: 10px;
      }
        .trade_button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: rgb(17, 17, 17);
        background-color: rgb(73, 68, 107);
        text-align: center;
        cursor: pointer;
        width: 50%;
        font-weight: 600;
        font-size: 18px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 250px;
        margin-top: 10px;
        border-radius: 10px;
        float: right;
      }


        button:hover, a:hover {
            opacity: 0.7;
        }

        a {
        text-decoration: none;
        font-size: 22px;
        color: black;
      }
      .grid_user {
        display: flex;
        margin-right: 40px;
        justify-content: space-around;
      }
      .name {
        text-align: left;
        font-weight: 700;
      }
      .form_form{
          padding: 50px;
  background: #ccc;
  position: fixed; top: 50%; left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
border-radius: 10px;
      }
      .form_button{
          margin:10px 0;
          border-radius: 10px;
          appearance:none;
          -webkit-appearance:none;
          padding:10px;
          border:none;
          background-color:#343a40;
          color:#fff;
          font-weight:600;
          width:100%;
      }
      h2 {
        text-align: center;
      }
      .page_userProfile {
        display: flex;
        justify-content: space-between;
      }
      .card_userProfile {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 500px;
          text-align: center;
        padding: 10px;
        background: white;
        border-radius: 5px;
          margin: auto auto auto 30px;
      }

      .card2_userProfile {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        margin: auto;
        text-align: center;
        padding: 10px;
        background: white;
        border-radius: 5px;
        margin-right: 30px;
        margin-left: 20px;
      }

      .blok2_userProfile {
        margin-right: 30px;
        margin-left: 20px;
      }

      .title_userProfile {
        color: grey;
        font-size: 18px;
      }

      button_userProfile {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: rgb(17, 17, 17);
        background-color: rgb(115, 105, 177);
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-weight: 500;
        font-size: 18px;
        border-radius: 10px;
      }

      a {
        text-decoration: none;
        font-size: 22px;
        color: black;
      }

      button_userProfile:hover,
      a:hover {
        opacity: 0.7;
      }

      body {
        background: rgb(152, 202, 202);
      }

      .name_userProfile {
        text-align: left;
        font-weight: 700;
      }
      .book_name_userProfile {
        text-align: left;
      }
      .card_userProfile img {
        float: center;
        max-width: 1000px;
        width: 100%;
        height: 100%;
      }
      .knopki_userProfile {
        display: flex;
        justify-content: space-evenly;
      }
    </style>


  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <a  href="{% url 'catalog:main'%}" class="navbar-brand mb-1">BookChange</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
            {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="nav navbar-nav me-auto mb-auto">
                <li>
                    <a href="{% url 'catalog:profile' user.id %}" class="nav-link small">Мой профиль</a>

                </li>
                <li>
                    <a href="{% url 'messenger:dialogs'%}" class="nav-link small">Мои сообщения</a>
                </li>

                <li>
              <a href="" class="nav-link small" data-bs-toggle="modal" data-bs-target="#exampleModal">Книга месяца</a>
            </li>

        </ul>
            <form action="m" class="">

                    <a href="{% url 'catalog:addBook'%}" class="nav-link small">Добавить книгу</a>
        </form>
        </div>
            {% endif %}
        </div>

    </nav>
    <div class="modal fade" tabindex="-1" id="exampleModal" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Книга месяца</h5>
          </div>
          <div class="modal-body">
            <div class="container-fluid">
              <form>
                <div class="card">
                    <img src="{{MEDIA_URL}}{{ book_of_month.image.url}}" alt="1984" style="width:100%">
                    <h1>{{book_of_month.title}}</h1>
                    <h2>{{book_of_month.author}}</h2>
                    <p class="title_card">{% for g in book_of_month.genre.all %} {{ g.genreName }}, {% endfor %}</p>
                    <p>{{book_of_month.summary}}</p>
                </div>
              </form>
            </div>
        </div>


          </div>
        </div>
      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  {% block content %}

    {% endblock %}
  </body>
</html>

bookchange/catalog/templates/catalog/profile_confirm_delete.html
{% extends "catalog/index.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

bookchange/catalog/templates/catalog/profile_of_user.html
{% extends 'catalog/index.html' %}
{% block title %}
Профиль {{user.username}}
{% endblock %}
  {% block content %}
<style type="text/css">
.card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 500px;
        margin: auto;
        text-align: center;
        padding: 10px;
      }

      .title {
        color: grey;
        font-size: 18px;
      }

      button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: rgb(17, 17, 17);
        background-color: grey;
        text-align: center;
        cursor: pointer;
        width: 50%;
        font-weight: 600;
        font-size: 18px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 281px;
        margin-left: 11.80%;
        margin-top: 10px;
        border-radius: 10px;
      }
      button_profile {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: rgb(17, 17, 17);
        background-color: rgb(73, 68, 107);
        font-weight: 600;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
        border-radius: 10px;
        margin-top: 10px;
      }

      a {
        text-decoration: none;
        font-size: 22px;
        color: black;
      }

      button:hover,
      a:hover {
        opacity: 0.7;
      }

      .container_book {
        align-self: flex-start;
        border: 2px solid #dedede;
        background-color: #f1f1f1;
        border-radius: 5px;
        padding: 10px;
        margin: 5px 0;
      }

      /* Clear floats */
      .container_book::after {
        content: "";
        clear: both;
        display: table;
      }

      /* Style images */
      .container_book img {
        float: left;
        max-width: 100px;
        width: 100%;
        height: 100%;
        margin-right: 20px;
        border-radius: 10%;
      }

      .book_name {
        font-weight: bold;
        margin-top: 12px;
        color: black;
      }

      .book_author {
        padding-top: 0px;
        color: rgb(82, 81, 81);
        margin-top: 15px;
      }

      .book_genre {
        color: rgb(146, 150, 146);
        padding-left: 120px;
      }

      .grid_user {
        display: flex;
        margin-right: 40px;
        justify-content: space-around;
      }

    </style>
  <div class="space1">
       <div class="grid_user">
        <div class="card">
            <img src="{{MEDIA_URL}}{{ profile.image.url }}"
                 style="width: 100%"/>
            <h1>{{user.username}} </h1>
            {% if request.user.id == profile.user.id %}
            <form action="{% url 'catalog:updateProfile' request.user.id %}"><button class="form_button">Изменить информацию о себе</button></form>
            {% endif %}
        </div>

        <div class="container_book">
          <h3>Книги пользователя</h3>
            {% if not books.count %}
            <p>Пусто :(</p>
            {% endif %}

            {% for book in books %}{% include 'catalog/book-item.html' with book_item=book %}{% endfor %}
        </div>
      </div>

</div>
{% endblock %}

bookchange/catalog/templates/catalog/tmp.html
{% extends 'catalog/index.html' %}
{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please log in with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'catalog:login' %}">
{% csrf_token %}
<table>

<tr>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</tr>

<tr>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
  У вас нет аккаунта?  <a href="{% url 'catalog:reg'%}" class="text-danger">Зарегестрироваться</a>
</form>