bookchange/bookchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(("catalog.urls", 'catalog'), namespace='catalog')),
                  path('', include(("messenger.urls", 'messenger'), namespace='messenger')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookchange/catalog/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('reg/', views.RegistrationView.as_view(), name='reg'),

    path('', login_required(views.MainListView.as_view()), name='main'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('book/create/', login_required(views.BookCreateView.as_view()), name='addBook'),
    path('book/<int:pk>', login_required(views.book), name='book'),
    path('book/<int:pk>/update', login_required(views.BookUpdateView.as_view()), name='updateBook'),
    path('book/<int:pk>/delete', login_required(views.BookDeleteView.as_view()), name='deleteBook'),

    path('author/create/', login_required(views.AuthorCreateView.as_view()), name='addAuthor'),
    path('author/<int:pk>/update', login_required(views.AuthorUpdateView.as_view()), name='updateAuthor'),
    path('author/<int:pk>/delete', login_required(views.AuthorDeleteView.as_view()), name='deleteAuthor'),

    path('profile/create/', login_required(views.ProfileCreateView.as_view()), name='addProfile'),
    path('profile/<int:pk>', login_required(views.profile), name='profile'),
    path('profile/<int:pk>/update', login_required(views.ProfileUpdateView.as_view()), name='updateProfile'),

    path('review/create/<int:pk>', login_required(views.ReviewCreateView.as_view()), name='addReview'),
    path('review/<int:pk>/update', login_required(views.ReviewUpdateView.as_view()), name='updateReview'),
    path('review/<int:pk>/delete', login_required(views.ReviewDeleteView.as_view()), name='deleteReview'),

]

bookchange/messenger/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('dialogs/', login_required(views.DialogsView.as_view()), name='dialogs'),
    path('dialogs/create/<int:user_id>/<int:book_id>',
         login_required(views.CreateDialogView.as_view()), name='create_dialog'),
    path('dialogs/<int:chat_id>', login_required(views.MessagesView.as_view()), name='dialog'),
]

bookchange/messenger/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
# noinspection PyUnresolvedReferences
from catalog.models import Book


# Во-первых чаты могут быть двух видов. Первый - это личная беседа двух человек. Второй вид - это коллективый чат. Реализован только диалог, чат будет потом но кирпичик уже сделан
class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = ((DIALOG, 'Dialog'), (CHAT, 'Chat'))

    type = models.CharField('Тип', max_length=1, choices=CHAT_TYPE_CHOICES, default=DIALOG)

    members = models.ManyToManyField(User)

    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    trade_owner = models.BooleanField(default=False)
    trade_customer = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'

    def get_absolute_url(self):
        return reverse('messenger-message', args=[str(self.id)])

    def __str__(self):
        # noinspection PyUnresolvedReferences
        return str(self.id)


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField("Message")
    pub_date = models.DateTimeField("Date", default=timezone.now)
    is_readed = models.BooleanField("Прочитано", default=False)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['pub_date']

    def __str__(self):
        return self.message

bookchange/messenger/forms.py
from django.forms import ModelForm
from .models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

bookchange/messenger/views.py
from catalog.models import Book, BookOfMonth
from django.db.models import Count
from django.db.models.functions import datetime
from django.shortcuts import render, redirect
from django.views import View

from .forms import MessageForm
from .models import *


def get_book_of_month():
    today = datetime.datetime.now()
    return BookOfMonth.objects.get(dayOfBook__year=today.year, dayOfBook__month=today.month)


# Для получения списка всех диалогов, в которых задействован пользователь, необходимо провести фильтрацию всех чатов
# по участникам, то есть по Many-toMany полю members. В данном случае у меня меня имеется шаблон для диалогов,
# в который я передаю авторизованного пользователя и список чатов. Активный пользователь будет нужен для корректного
# отображения прочитанных и не прочитанных сообщений в списке диалогов.
class DialogsView(View):
    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        return render(request, 'messenger/dialogs.html', {'user_profile': request.user, 'chats': chats,
                                                          'book_of_month': get_book_of_month()})


# Для отображения текущего диалога и сообщений уже потребуется более сложная логика. Дело в том, что здесь доступ к
# чату осуществляется по ID, но необходимо сделать не только попытку получения диалога, но и проверить, существует ли
# в списке участников пользователь, который пытается попасть в данный чат. Если он не существует в списке участников,
# то доступ в данный чат ему запрещён. Помимо прочего в этом же представлении обрабатывается отсылка сообщений и
# пометка сообщений прочитанными.
class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_readed=False).exclude(author=request.user).update(is_readed=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None
        return render(request, 'messenger/messages.html',
                      {'user_profile': request.user, 'chat': chat, 'form': MessageForm(),
                       'book_of_month': get_book_of_month()})

    def post(self, request, chat_id):
        if 'message' in request.POST:
            form = MessageForm(data=request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.chat_id = chat_id
                message.author = request.user
                message.save()
            return redirect(reverse('messenger:dialog', kwargs={'chat_id': chat_id}))
        else:
            chat = Chat.objects.get(id=chat_id)
            book = Book.objects.get(chat=chat)
            owner = book.owner
            if owner == request.user:
                chat.trade_owner = not chat.trade_owner
            else:
                chat.trade_customer = not chat.trade_customer
            if chat.trade_customer and chat.trade_owner:
                book.owner = chat.members.exclude(id=owner.id).first()
                book.save()
                message = Message.objects.create(chat=chat, author=owner, message="Обмен произошел. Новый владелец:" + book.owner.username)
                message.save()
                chat.trade_owner = not chat.trade_owner
                chat.trade_customer = not chat.trade_customer
            chat.save()
            return redirect(reverse('messenger:dialog', kwargs={'chat_id': chat_id}))


# На данный момент реализован лишь один метод для начала беседы с пользователем. Необходимо перейти на страницу
# пользователя и нажать на кнопку "Написать сообщение", тогда через ссылку будет отправлен запрос, в котором будет
# создан чат или найден уже существующий чат с этим пользователем. Здесь испольуется проверка на то, является ли чат
# диалогом или беседой нескольких пользователей. Что позволяет несколько упростить поиск необходимого диалога.
class CreateDialogView(View):
    def get(self, request, user_id, book_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id], type=Chat.DIALOG).annotate(
            c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Chat.objects.create(book=Book.objects.get(id=book_id))
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('messenger:dialog', kwargs={'chat_id': chat.id}))

bookchange/messenger/templates/messenger/dialogs.html
   {% extends "catalog/index.html" %}
{% load messenger_extra %}
   {% load bootstrap3 %}
   {% block title %}
   Мессенджер
{% endblock %}
     {% block content %}
    <div class="panel">
            {% load tz %}
            {% if chats.count == 0 %}
                <div class="panel panel-body">"Нет ни одного начатого диалога"</div>
            {% endif %}
            {% for chat in chats %}
                {% if chat.message_set.count != 0 %}
                    {% with last_message=chat.message_set.last %}
                        {% get_companion user chat as companion %}
                        <a class="list-group-item {% if companion == last_message.author and not last_message.is_readed %}unreaded{% endif %}" href="{% url 'messenger:dialog' chat.id %}">
                            <div class="reply-body">
                                <ul class="list-inline">
                                    <li class="drop-left-padding">
                                        <strong class="list-group-item-heading">{{ companion.username }}</strong>
                                    </li>
                                    <li class="pull-right text-muted"><small>{{ last_message.pub_date|localtime }}</small></li>
                                </ul>
                                {% if companion != last_message.author %}
                                    <div>
                                        <div class="attached-reply-body {% if not last_message.is_readed %}unreaded{% endif %}">{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                    </div>
                                {% else %}
                                    <div>{{ last_message.message|truncatechars_html:"200"|safe|striptags }}</div>
                                {% endif %}
                            </div>
                        </a>
                    {% endwith %}
                {% endif %}
            {% endfor %}
        </div>
   {% endblock %}

bookchange/messenger/templates/messenger/message.html
{% url 'catalog:profile' message_item.author.username as the_user_url%}
{% load bootstrap3 %}
{% load tz %}
    <div class="container_message{% if not message_item.author == user %} darker {% endif %}">
        <a href="{% url 'catalog:profile' message_item.author_id%}"><img class="rounded-circle" src="{{MEDIA_URL}}{{ message_item.author.profile.image.url }}"></a>
        <div class="reply-body">
            <ul class="list-inline">
                <li class="drop-left-padding">
                    <strong class="list-group-item-heading"><a href="{% url 'catalog:profile' message_item.author_id%}">{{ message_item.author.username }}</a></strong>
                </li>
                <li class="pull-right text-muted"><small>{{ message_item.pub_date|localtime }}</small></li>
            </ul>
            <div>{{ message_item.message|safe }}</div>
        </div>
    </div>

bookchange/messenger/templates/messenger/messages.html
{% extends "catalog/index.html" %}
{% load bootstrap3 %}
{% block title %}   Диалог   {% endblock %}
{% block content %}
    {% if not chat %}
        <div class="panel panel-body">
            Невозможно начать беседу.
        </div>
    {% else %}
        {% load tz %}
        {% if chat %}
<div class ="space1">
            <div class="container_trade">
          <div class="text">
                <img src="{{MEDIA_URL}}{{ chat.book.image.url}}" alt="bookPuc"/>
                <p class="book_name"><a href="{% url 'catalog:book' chat.book.id %}">{{ chat.book.title }}</a></p>
                <p class="book_author">Автор: {{ chat.book.author }}</p>
                <p class="book_genre"> Жанры:{% for g in chat.book.genre.all %}
                                    {{ g.genreName }}
                                {% endfor %}</p>
            </div>
                <form id="trade-form" method = "post" name="trade">
                    {% csrf_token %}
                    <button class="trade_button">Обменяться</button>
                </form>
                {% if chat.trade_owner == 1 %}
                    <a>{{chat.book.owner.username}} предложил обмен</a>
                {% endif %}
                {% if chat.trade_customer == 1 %}
                    {% for member in chat.members.all %}
                        {% if member == chat.book.owner %}

                        {% else %}
                <a>{{member}} предложил обмен</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
        </div>
    </div>
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                            {% include 'messenger/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="footer">
            <form id="message-form" class="form-control col-8 col-sm-9 col-md-8" method="post" name="message">

                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>Отправить</button>
            </form>
        </div>
    {% endif %}
{% endblock %}